name: service_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  flutter_svg: ^1.0.3
  equatable: ^2.0.5
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  dotted_border: ^2.1.0
  table_calendar: ^3.0.0
  sqflite: ^2.3.3+1
  build_runner: ^2.4.6
  adaptive_action_sheet: ^2.0.2
  image_picker: ^1.0.4
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  flutter_cupertino_datetime_picker:
  jiffy: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  freezed: ^2.4.2
  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
